### ISSUE TITLE
Add some context to readme

### ISSUE THREAD

**Issue by lognaturel** [grzesiek2010/collectTester#1]
Small things like 
- it's possible to build apps that interact with Collect through intents
- this app shows the intents Collect responds to and a description of what they do
- another way to build integrations is to use the external data widgets. I'd link this readme to the counter repo and that one to this one so it tells a nice story about integrating with Collect.

**Comment by grzesiek2010** [comment]
@lognaturel 
I think that's enough. What do you think?

**Comment by lognaturel** [comment]
Great!
