### ISSUE TITLE
User is able to edit the form that was sent if user opens it from 'Instances List' view

### ISSUE THREAD

**Issue by mmarciniak90** [grzesiek2010/collectTester#10]
### Use Case
1. User finishes form
2. User sends finished form
3. User clicks on 'Instances List' button
4. User sees list of all forms, also sent forms

### Actual Result
1. User selects sent form in 'Instances List'
2. User is able to edit this form

### Expected Result
@lognaturel I'm not sure what is expected. I can give my suggestions:

**Option 1.** 
'Instances List' shows **only** forms which are finished and saved as incomplete

**Option 2.**
'Instances List' shows all forms but recognizes the status of the form.

- When user opens finished or saved as incomplete form user is able to edit it.
User sees 'Go to Start' / 'Go TO End' buttons.
![screenshot_2017-10-04-11-21-17](https://user-images.githubusercontent.com/3907554/31171037-b581caa4-a8fe-11e7-8697-a7fd9fe7a21d.png)

- When user opens sent form user is not able to edit it.
User sees only 'Exit' button
![screenshot_2017-10-04-11-21-30](https://user-images.githubusercontent.com/3907554/31171100-de276b8a-a8fe-11e7-81fe-7dc8eab6c299.png)

**Comment by grzesiek2010** [comment]
@mmarciniak90 @lognaturel My intent was to display only instances we can edit like in ODK when you click on "Edit Saved Form". So I should check statuses. Do you agree with me @lognaturel ?

**Comment by lognaturel** [comment]
Yes, that sounds like a good approach! Good catch @mmarciniak90!
