### ISSUE TITLE
Add form download intent test

### ISSUE THREAD

**Issue by ekigamba** [grzesiek2010/collectTester#18]
This demonstrates how this [PR](https://github.com/opendatakit/collect/pull/2348) from [this issue](https://github.com/opendatakit/collect/issues/2339) works. See more in the above links.

### IMPLEMENTATION

The tester should be able to select the download form on the main page. The user will be taken to another page where they can enter the form_id of the form they want to download.  Above the *download button* will be status text with the formID and current status if any.

**Comment by grzesiek2010** [comment]
Fixed in #27
